### ISSUE TITLE
Mod Crashed in modpack

### ISSUE THREAD

**Issue by BlueBerrySoda03** [Siepert123/create-legacy#2]
as the description says, I don't know why, or how it did it. The logs are here:

[crash-2024-07-13_23.01.35-client.txt](https://github.com/user-attachments/files/16215502/crash-2024-07-13_23.01.35-client.txt)
[latest.log](https://github.com/user-attachments/files/16215504/latest.log)

**Comment by BlueBerrySoda03** [comment]
yep! I loaded in with no issues.
     I know this mod is early in development, but in the future, can you add a config file and ways to disable all worldgen (aka ores and the custom stone). I'm making a modpack currently and I don't want 7 different types of copper, lol.

**Comment by Metaa4245** [comment]
> I'm making a modpack currently and I don't want 7 different types of copper, lol.

use [CoFH World](https://www.curseforge.com/minecraft/mc-mods/cofh-world) to configure world generation, and besides, they're all compatible if they have an ore dictionary entry
